name: Hello-World-App

on:
  push:
    branches: [ "main" ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ "main" ]

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io
  # github.repository as <account>/<repo>
  IMAGE_NAME: ${{ github.repository }}

jobs:
  Build-Hello-World-App-and-Run-Trivy-Scan:
    permissions:
      contents: read
      security-events: write
      actions: read
    runs-on: ubuntu-latest

    steps:
      # Should this section be a comment?
      # Or should this be part of the pipeline?
      # - name: Checkout code
      #   uses: actions/checkout@v4

      - name: Troubleshooting assistance
        run: |
          ls -l $GITHUB_WORKSPACE
          printenv 

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Pipeline will break at this stage without certain token permissions associated. 
      # To create a new GitHub token, follow these instructions for creating a personal access token (classic). 
      # https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/managing-your-personal-access-tokens
      # The permissions required is having access to the repo, the workflow, and the write:packages.
      # If you need assistance with this, please let me know, but read the instructions first before asking.
      #
      # After creating your personal access token, you then need to copy it and paste it as a secret on GitHub Actions.
      - name: Log in to {{ env.REGISTRY }}
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.REGISTRY_TOKEN }}

      - name: Extract Docker image metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ github.repository }}
 
      - name: Build and push Docker image
        if: ${{ github.event_name != 'pull_request' }}
        uses: docker/build-push-action@v6
        with:
          context: ${{ github.workspace }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@0.28.0
        with:
          image-ref: '${{ steps.meta.outputs.tags }}'
          format: 'template'
          template: '@/contrib/sarif.tpl'
          output: 'hello-world-app.sarif'

      # Is the file name correct?
      # The output of the job called Run Trivy vulnerability scanner doesn't match the sarif_file. 
      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: 'hello-world-broken-app.sarif'